# Workflow for building and deploying the opkg repo to GitHub Pages
name: build and update repo

on:
  push:
    branches: ["main"]

  schedule:
    # Runs "At 06:30 on Tuesday." (see https://crontab.guru)
    - cron: '30 6 * * 2'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build IPK files
        run: ./build.sh "${{ github.event_name }}"

      - name: Sign Packages index
        if: ${{ env.SIGNING_KEY != '' }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          sudo apt-get install -yqq signify-openbsd
          TMPKEY=$(mktemp)
          echo "$SIGNING_KEY" > "$TMPKEY"
          signify-openbsd -S -s "$TMPKEY" -m packages/19.07/Packages -x packages/19.07/Packages.sig
          rm -f "$TMPKEY"

      - name: Check new package existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "packages/19.07/Packages"

      - name: Prep GH Pages Directory
        if: ${{ (github.ref == 'refs/heads/main') && (steps.check_files.outputs.files_exists == 'true') }}
        run: |
          cp -r ./html ./gh_pages
          mv ./packages/ gh_pages/packages/
          cp -r ./keys gh_pages/keys
          ./tools/gen_directory_listing.sh ./gh_pages/packages/19.07/

      - name: Upload Pages artifact
        if: ${{ (github.ref == 'refs/heads/main') && (steps.check_files.outputs.files_exists == 'true') }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./gh_pages

      - name: Deploy to GitHub Pages
        if: ${{ (github.ref == 'refs/heads/main') && (steps.check_files.outputs.files_exists == 'true') }}
        id: deployment
        uses: actions/deploy-pages@v5
